<script type="text/javascript">
require([
    'jquery',
    'mage/utils/wrapper'
], function ($, wrapper) {
    var simpleSku = $("div[itemprop='sku']").text();
    var url= BASE_URL + "/altitudep21/index/getajax";
    var basePrice = 0;
    var formatter = new Intl.NumberFormat('en-US', {
        style: 'currency',
        currency: 'USD',
        minimumFractionDigits: 2,
    });

    $.ajax({
        url: url,
        type: "GET",
        data: {
            sku: simpleSku,
        }
    }).done(function(msg) {

        basePrice = parseFloat(msg);
        if (basePrice>0) {
            basePrice = formatter.format(basePrice);
            $('.product-info-price .price-box .price-container .price-wrapper .price').html(basePrice);
            $('.product-info-price .price-box .price-container .price-wrapper:first ').data('priceAmount',basePrice)
        }
    });
});

</script>
